version: '3.4'

services:
  django-common:
    build:
      context: .
      dockerfile: docker-files/app/common.Dockerfile
    image: lms-backend-django-prod-deps
    command: /bin/true
  uwsgi:
    container_name: lms-django
    build:
      context: .
      dockerfile: docker-files/app/Dockerfile
      args:
        - BASE_IMAGE=lms-backend-django-prod-deps
        - FRONTEND_IMAGE=lms-webpack-bundles
        - DJANGO_STATIC_ROOT=/var/www/static/
        - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
    image: lms-backend-django
    restart: always
    environment:
      - DATABASE_URL=postgresql://csc:FooBar@db:5432/cscdb
      - PROJECT_MODULE_NAME=compscicenter_ru
      - REDIS_HOST=lms-redis-cluster
      - REDIS_PASSWORD=secret-password
    volumes:
      - static-data:/var/www/static
    depends_on:
      - db
      - redis
      - django-common
  django-tests:
    container_name: lms-django-tests
    build:
      context: .
      dockerfile: docker-files/app/dev.Dockerfile
      args:
        - BASE_IMAGE=lms-backend-django-prod-deps
    image: lms-backend-django-tests
    environment:
     - PROJECT_MODULE_NAME=compscicenter_ru
     - REDIS_HOST=lms-redis-cluster
     - REDIS_PASSWORD=secret-password
    depends_on:
      - db
      - redis
      - uwsgi
  rqworker:
    container_name: lms-task-queue
    image: lms-backend-django
    restart: always
    environment:
      - DEBUG=0
      - REDIS_HOST=lms-redis-cluster
      - REDIS_PASSWORD=secret-password
    command: python manage.py rqworker high default
    depends_on:
      - uwsgi
  cron:
    # requires: django-rq-scheduler
    container_name: lms-cron
    image: lms-backend-django
    restart: always
    environment:
      - DEBUG=0
      - REDIS_HOST=lms-redis-cluster
      - REDIS_PASSWORD=secret-password
    command: python manage.py cron_tasks
    depends_on:
      - uwsgi
      - redis
  nginx:
    container_name: lms-nginx
    build:
      context: ./docker-files/nginx
      dockerfile: Dockerfile
    image: lms-backend-nginx
    ports:
      - "80:80"
    volumes:
      - static-data:/var/www/static
      - media-data:/var/www/media
    depends_on:
      - redis
      - uwsgi
  db:
    container_name: db
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: csc
      POSTGRES_DB: cscdb
      POSTGRES_PASSWORD: FooBar
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  redis:
    container_name: lms-redis-cluster
    image: "redis:6-alpine"
    command: sh -c 'if [ "x$${REDIS_PASSWORD}" = "x" ]; then redis-server --appendonly yes; else redis-server --appendonly yes --requirepass $$REDIS_PASSWORD; fi'
    expose:
      - 6379
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=secret-password

volumes:
  static-data:
  media-data:
    name: lms-media
    external: true
  redis-data:
    name: lms-redis-data
    external: true
  postgres-data:
  lms-repository:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .
